name: Events

on:
  push:
    branches: main
    
jobs:
  Validate-tag:
    runs-on: ubuntu-18.04

    steps:
      - name: Get project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Versioning
        id: app_version
        run: |
          chmod +x ./.github/scripts/version_validation.sh
          ./.github/scripts/version_validation.sh
