name: Delivery pipeline

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: avakar/create-deployment@v1
        id: deployment
        with:
          auto_merge: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: echo deployment creation
        run: |
          echo "ID" ${{ steps.deployment.outputs.deployment_id }}
          echo "deploy URL" ${{ steps.deployment.outputs.deployment_url }}
          echo "status URL" ${{ steps.deployment.outputs.statuses_url }}
          
      - id: set_state_in_progress
        name: Set deployment status to [in_progress]
        uses: rsotnychenko/deployment-status-update@0.2.0
        with:
          run_id: ${{ github.run_id }}
          status: in_progress
          deployment_status_url: ${{ steps.deployment.outputs.statuses_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: test
        run: |
          echo "testing"
          sleep 60
          
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
        
      - id: set_state_final
        if: always()
        name: Set deployment status
        uses: rsotnychenko/deployment-status-update@0.2.0
        with:
          status: ${{ job.status }}
          run_id: ${{ github.run_id }}
          description: ${{ github.workflow }} ${{ github.log_url }} 
          deployment_status_url: ${{ steps.deployment.outputs.statuses_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
